# Site settings
author: Haidy Farahat
title: Software Engineering
header-img: img/home-bg.png
email: haidyfarahat@gmail.com
copyright_name: Haidy Farahat
description: > # this means to ignore newlines until "baseurl:"
  Blogs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HaidyF

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
